# Generated by Django 4.0.4 on 2022-05-17 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('original_img', models.ImageField(upload_to='image', verbose_name='Original')),
                ('enc_img', models.ImageField(upload_to='encode', verbose_name='Encrypted')),
                ('dec_img', models.ImageField(upload_to='decode', verbose_name='Decrypted')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('alg_var', models.CharField(choices=[('GOSTCRYPTO', 'GOSTCRYPTO'), ('STUDENT', 'STUDENT')], max_length=255)),
                ('date_upload', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
